---
- name: Make sure apt does SSL
  apt:
    name: apt-transport-https
    state: present

- name: Import apt keys
  apt_key:
    keyserver: '{{ docker_apt_keyserver }}'
    id: '{{ docker_apt_key_id }}'

- name: Add apt repository
  apt_repository:
    repo: deb {{ docker_apt_repo }} {{ ansible_distribution|lower }}-{{ ansible_distribution_release|lower }} {{ docker_apt_channel }}
    filename: docker
    update_cache: yes

- name: Install docker
  apt:
    name: docker-engine={{ docker_version }}
    state: present

- name: Hold docker version
  dpkg_selections:
    name: docker-engine
    selection: hold
