---
- name: Make sure apt does SSL
  apt:
    name: apt-transport-https
    state: present

- name: Import apt keys
  apt_key:
    keyserver: '{{ docker_apt_keyserver }}'
    id: '{{ docker_apt_key_id }}'

- name: Add apt repository
  apt_repository:
    repo: '{{ docker_apt_repo }}'
    filename: docker
    update_cache: yes

- name: Install docker
  apt:
    name: docker-engine={{ docker_version }}
    state: present
  notify: restart docker

# Installing new version switches 'hold' to 'install', but this should
# idempotently restore the hold, even if we've just updated the version.
- name: Hold docker version
  dpkg_selections:
    name: docker-engine
    selection: hold
