---
- name: Make sure apt does SSL
  apt:
    name: apt-transport-https
    state: present
  when: '"https" in docker_apt_repo'

- name: Import apt key from keyserver
  apt_key:
    keyserver: '{{ docker_apt_keyserver }}'
    id: '{{ docker_apt_key_id }}'
  when: docker_apt_keyserver

- name: Import apt key from URL
  apt_key:
    url: "{{ docker_apt_key_url }}"
    state: present
  when: docker_apt_key_url is defined

- name: Add apt repository
  apt_repository:
    repo: '{{ docker_apt_repo }}'
    filename: docker
    update_cache: yes

- name: Pin docker package version
  copy:
    dest: /etc/apt/preferences.d/docker
    content: |
      Package: {{ docker_package }}
      Pin: version {{ docker_version }}
      Pin-Priority: 1002

- name: Install docker
  apt:
    name: "{{ docker_package }}={{ docker_version }}"
    state: present
  notify: restart docker
