---
- name: Make sure yum can lock versions
  yum:
    name: yum-plugin-versionlock
    state: present

- name: Add yum repository
  yum_repository:
    name: docker
    description: Docker project repository
    baseurl: "{{ docker_yum_repo }}"
    gpgcheck: "{{ docker_yum_gpg_check }}"
    gpgkey: "{{ docker_yum_gpg_key }}"

- name: Unlock docker version in YUM
  command: yum versionlock delete {{ docker_package }}
  args:
    warn: false
  changed_when: false
  ignore_errors: yes

- name: Install docker
  yum:
    name: "{{ docker_package }}-{{ docker_version }}"
    state: present
  notify: restart docker

- name: Lock docker version
  command: yum versionlock {{ docker_package }}
  args:
    warn: false
  changed_when: false

- name: Install EPEL
  yum:
    name: epel-release
    state: present
  when: docker_install_docker_py and docker_install_epel
