Vagrant.configure(2) do |config|
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.cpus = 3
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "bento/ubuntu-16.04"
    ubuntu.vm.network "private_network", ip: "192.168.123.2"
    ubuntu.vm.provision "shell", inline: "sudo apt-get install -y python"
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "bento/centos-7.3"
    centos.vm.network "private_network", ip: "192.168.123.3"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
